services:
    _defaults:
        public: true

    coreshop.resource_registry:
        alias: CoreShop\Component\Resource\Metadata\RegistryInterface
        deprecated: { package: "coreshop/resource-bundle", version: "3.0", message: 'The "%alias_id%" service alias is deprecated since CoreShop 3.0 and will be removed with 3.1, use CoreShop\Component\Resource\Metadata\RegistryInterface instead' }

    coreshop.admin_controller.resource_settings:
        alias: CoreShop\Bundle\ResourceBundle\Controller\ResourceSettingsController
        deprecated: { package: "coreshop/resource-bundle", version: "3.0", message: 'The "%alias_id%" service alias is deprecated since CoreShop 3.0 and will be removed with 3.1, use CoreShop\Bundle\ResourceBundle\Controller\ResourceSettingsController instead' }

    coreshop.resource.helper.form_error_serializer:
        alias: CoreShop\Bundle\ResourceBundle\Form\Helper\ErrorSerializer

    coreshop.translation_locale_provider.pimcore:
        alias: CoreShop\Component\Resource\Translation\Provider\PimcoreTranslationLocaleProvider
        deprecated: { package: "coreshop/resource-bundle", version: "3.0", message: 'The "%alias_id%" service alias is deprecated since CoreShop 3.0 and will be removed with 3.1, use CoreShop\Component\Resource\Translation\Provider\TranslationLocaleProviderInterface instead' }
