imports:
    - { resource: "services/routing.yml" }
    - { resource: "services/controller.yml" }

parameters:
  coreshop.admin.route.base: /admin/coreshop
  jms_serializer.camel_case_naming_strategy.class: JMS\Serializer\Naming\IdenticalPropertyNamingStrategy

services:
  coreshop.object_service:
    class: CoreShop\Component\Resource\Pimcore\ObjectService

  coreshop.resource_registry:
    class: CoreShop\Component\Resource\Metadata\Registry

  coreshop.jms_serializer.handler.relation:
      class: CoreShop\Bundle\ResourceBundle\Serialization\RelationsHandler
      arguments:
      - "@doctrine.orm.entity_manager"
      tags:
      - { name: jms_serializer.handler, type: relation, direction: serialization, format: json, method: serializeRelation}
      - { name: jms_serializer.handler, type: relation, direction: deserialization, format: json, method: deserializeRelation}
      - { name: jms_serializer.handler, type: relation<?>, direction: serialization, format: json, method: serializeRelation}
      - { name: jms_serializer.handler, type: relation<?>, direction: deserialization, format: json, method: deserializeRelation}

  jms_serializer.object_constructor:
    alias: jms_serializer.doctrine_object_constructor
    public: false

  coreshop.form.type_extension.form.request_handler:
    class: CoreShop\Bundle\ResourceBundle\Form\Extension\HttpFoundation\HttpFoundationRequestHandler
    decorates: form.type_extension.form.request_handler
    decoration_priority: 256
    public: false

  coreshop.registry.resource.installers:
    class: CoreShop\Component\Registry\PrioritizedServiceRegistry
    arguments:
      - CoreShop\Bundle\ResourceBundle\Installer\ResourceInstallerInterface
      - 'coreshop-resource-installer'

  coreshop.resource.installer.classes:
    class: CoreShop\Bundle\ResourceBundle\Installer\PimcoreClassInstaller
    arguments: ['%coreshop.pimcore%', '@kernel']
    tags:
      - { name: 'coreshop.resource.installer', type: 'classes', priority: 100}

  coreshop.resource.installer.routes:
    class: CoreShop\Bundle\ResourceBundle\Installer\PimcoreRoutesInstaller
    arguments: ['@kernel']
    tags:
      - { name: 'coreshop.resource.installer', type: 'routes', priority: 200}

  coreshop.resource.installer.permissions:
    class: CoreShop\Bundle\ResourceBundle\Installer\PimcorePermissionInstaller
    arguments: ['%coreshop.resource.permissions%']
    tags:
      - { name: 'coreshop.resource.installer', type: 'permissions', priority: 200}

  coreshop.resource.installer:
    class: CoreShop\Bundle\ResourceBundle\Installer\CompositeResourceInstaller
    arguments:
      - '@coreshop.registry.resource.installers'

  coreshop.admin_controller.resource_settings:
    class: CoreShop\Bundle\ResourceBundle\Controller\ResourceSettingsController
    calls:
      - [setContainer, ['@service_container']]