services:
    _defaults:
        public: true

    coreshop.command.resource.installer:
        class: CoreShop\Bundle\ResourceBundle\Command\InstallResourcesCommand
        arguments:
            - '@coreshop.resource.installer'
        tags:
            - { name: console.command, command: 'coreshop:resources:install' }
