services:
    _defaults:
        public: true

    coreshop.registry.resource.installers:
        class: CoreShop\Component\Registry\PrioritizedServiceRegistry
        arguments:
            - CoreShop\Bundle\ResourceBundle\Installer\ResourceInstallerInterface
            - 'coreshop-resource-installer'

    CoreShop\Bundle\ResourceBundle\Installer\PimcoreClassInstaller:
        arguments:
            - '@kernel'
            - '@coreshop.class_installer'
        tags:
            - { name: coreshop.resource.installer, type: classes, priority: 100}

    CoreShop\Bundle\ResourceBundle\Installer\PimcoreRoutesInstaller:
        arguments:
            - '@kernel'
        tags:
            - { name: coreshop.resource.installer, type: routes, priority: 200}

    CoreShop\Bundle\ResourceBundle\Installer\PimcoreDocumentsInstaller:
        arguments:
            - '@kernel'
        tags:
           - { name: coreshop.resource.installer, type: documents, priority: 250}

    CoreShop\Bundle\ResourceBundle\Installer\PimcoreImageThumbnailsInstaller:
        arguments:
            - '@kernel'
        tags:
            - { name: coreshop.resource.installer, type: image_thumbnail, priority: 300}

    CoreShop\Bundle\ResourceBundle\Installer\PimcorePermissionInstaller:
        arguments:
            - '@kernel'
        tags:
            - { name: coreshop.resource.installer, type: permissions, priority: 350}

    CoreShop\Bundle\ResourceBundle\Installer\SqlInstaller:
        arguments:
            - '@kernel'
        tags:
           - { name: coreshop.resource.installer, type: sql, priority: 400}

    CoreShop\Bundle\ResourceBundle\Installer\PimcoreSharedTranslationsInstaller:
        arguments:
            - '@kernel'
            - 'Pimcore\Model\Translation\Website'
        tags:
           - { name: coreshop.resource.installer, type: translations, priority: 450}

    CoreShop\Bundle\ResourceBundle\Installer\PimcoreAdminTranslationsInstaller:
        arguments:
            - '@kernel'
            - 'Pimcore\Model\Translation\Admin'
        tags:
           - { name: coreshop.resource.installer, type: admin_translations, priority: 500}

    CoreShop\Bundle\ResourceBundle\Installer\PimcoreGridConfigInstaller:
        arguments:
            - '@kernel'
            - '@CoreShop\Component\Resource\Metadata\RegistryInterface'
            - '@pimcore.dao.object_manager'
            - '@CoreShop\Component\Pimcore\DataObject\GridConfigInstallerInterface'
            - '@CoreShop\Bundle\ResourceBundle\Installer\PimcoreClassInstaller'
        tags:
            - { name: coreshop.resource.installer, type: grid_config, priority: 200}

    coreshop.resource.installer: '@CoreShop\Bundle\ResourceBundle\Installer\CompositeResourceInstaller'
    CoreShop\Bundle\ResourceBundle\Installer\ResourceInstallerInterface: '@CoreShop\Bundle\ResourceBundle\Installer\CompositeResourceInstaller'
    CoreShop\Bundle\ResourceBundle\Installer\CompositeResourceInstaller:
        arguments:
            - '@coreshop.registry.resource.installers'
