services:
  coreshop.registry.resource.installers:
    class: CoreShop\Component\Registry\PrioritizedServiceRegistry
    arguments:
      - CoreShop\Bundle\ResourceBundle\Installer\ResourceInstallerInterface
      - 'coreshop-resource-installer'

  coreshop.resource.installer.classes:
    class: CoreShop\Bundle\ResourceBundle\Installer\PimcoreClassInstaller
    arguments: ['@kernel']
    tags:
      - { name: 'coreshop.resource.installer', type: 'classes', priority: 100}

  coreshop.resource.installer.routes:
    class: CoreShop\Bundle\ResourceBundle\Installer\PimcoreRoutesInstaller
    arguments: ['@kernel']
    tags:
      - { name: 'coreshop.resource.installer', type: 'routes', priority: 200}

  coreshop.resource.installer.permissions:
    class: CoreShop\Bundle\ResourceBundle\Installer\PimcorePermissionInstaller
    arguments: ['@kernel']
    tags:
      - { name: 'coreshop.resource.installer', type: 'permissions', priority: 300}

  coreshop.resource.installer.sql:
    class: CoreShop\Bundle\ResourceBundle\Installer\SqlInstaller
    arguments: ['@kernel']
    tags:
      - { name: 'coreshop.resource.installer', type: 'sql', priority: 400}

  coreshop.resource.installer:
    class: CoreShop\Bundle\ResourceBundle\Installer\CompositeResourceInstaller
    arguments:
      - '@coreshop.registry.resource.installers'