services:
    _defaults:
        public: true

    CoreShop\Bundle\ResourceBundle\Validator\Constraints\UniqueEntityValidator:
        tags:
            - { name: validator.constraint_validator, alias: coreshop.unique_entity }
