services:
    coreshop.validator.unique.registered_customer:
        class: CoreShop\Bundle\ResourceBundle\Validator\Constraints\UniqueEntityValidator
        arguments:
            - '@coreshop.repository.customer'
        tags:
            - { name: validator.constraint_validator, alias: coreshop.unique_entity }