services:
    coreshop.validator.unique_soentity:
        class: CoreShop\Bundle\ResourceBundle\Validator\Constraints\UniqueEntityValidator
        tags:
            - { name: validator.constraint_validator, alias: coreshop.unique_entity }