jms_serializer:
    metadata:
        directories:
            coreshop-resource:
                namespace_prefix: "Pimcore"
                path: "@CoreShopResourceBundle/Resources/config/serializer"

doctrine:
    dbal:
        types:
            pimcoreObject: CoreShop\Component\Resource\Doctrine\Type\PimcoreObject