jms_serializer:
    metadata:
        directories:
            pimcore:
                namespace_prefix: "Pimcore"
                path: "@CoreShopResourceBundle/Resources/config/serializer"

pimcore:
    objects:
        class_definitions:
            data:
                map:
                    coreShopSerializedData: CoreShop\Bundle\ResourceBundle\CoreExtension\SerializedData
